adaptivepayments-sdk-ruby/samples/config/routes.rb
AdaptivePaymentsSamples::Engine.routes.draw do
  post  "adaptive_payments/ipn_notify" => "adaptive_payments#ipn_notify", :as => :ipn_notify
  match "adaptive_payments(/:action)",  :controller => "adaptive_payments", :as => :adaptive_payments
  root :to => "adaptive_payments#index"
end

adaptivepayments-sdk-ruby/samples/app/models/adaptive_payments_samples/api_form_builder.rb
module AdaptivePaymentsSamples
  class APIFormBuilder < SimpleForm::FormBuilder
    def fields_for(member_name, member_object = nil, &block)
      member_object ||= ( object.send(member_name) || object.send("#{member_name}=", {}))
      member_options = object.class.members[member_name.to_sym]
      if member_options[:array]
        fields = []
        member_object.each_with_index do |obj, index|
          fields << super(member_name, obj, :index => index, &block)
        end
        fields.join.html_safe
      else
        super(member_name, member_object, &block)
      end
    end
    alias_method :simple_form_for, :fields_for
    alias_method :association, :fields_for

    def input(member_name, options = {})
      super(member_name, api_input_options(member_name, options))
    end

    def api_input_options(member_name, options = {})
      member_options      = object.class.members[member_name.to_sym]
      options[:label]   ||= member_name.to_s.underscore.humanize
      options[:wrapper] ||= :api_sample_form
      options[:required]  = !!member_options[:required] if options[:required].nil?
      if member_options[:type] < PayPal::SDK::Core::API::DataTypes::Enum
        options[:as] = ( member_options[:array] ? :check_boxes : :select )
        options[:collection] = member_options[:type].options
      elsif member_options[:type] == PayPal::SDK::Core::API::DataTypes::SimpleTypes::Boolean
        options[:as] = :select
        options[:collection] = [ true, false ]
      end
      options
    end
  end
end

adaptivepayments-sdk-ruby/samples/app/controllers/adaptive_payments_samples/adaptive_payments_controller.rb
require_dependency "adaptive_payments_samples/application_controller"

module AdaptivePaymentsSamples
  class AdaptivePaymentsController < ApplicationController
    include PayPal::SDK::AdaptivePayments

    def index
      redirect_to :action => :pay
    end

    def ipn_notify
      if PayPal::SDK::Core::API::IPN.valid?(request.raw_post)
        logger.info("IPN message: VERIFIED")
        render :text => "VERIFIED"
      else
        logger.info("IPN message: INVALID")
        render :text => "INVALID"
      end
    end

    def cancel_preapproval
      @cancel_preapproval = api.build_cancel_preapproval(params[:CancelPreapprovalRequest] || default_api_value)
      @cancel_preapproval_response = api.cancel_preapproval(@cancel_preapproval) if request.post?
    end

    def confirm_preapproval
      @confirm_preapproval = api.build_confirm_preapproval(params[:ConfirmPreapprovalRequest] || default_api_value)
      @confirm_preapproval_response = api.confirm_preapproval(@confirm_preapproval) if request.post?
    end

    def convert_currency
      @convert_currency = api.build_convert_currency(params[:ConvertCurrencyRequest] || default_api_value)
      @convert_currency_response = api.convert_currency(@convert_currency) if request.post?
    end

    def execute_payment
      @execute_payment = api.build_execute_payment(params[:ExecutePaymentRequest] || default_api_value)
      @execute_payment_response = api.execute_payment(@execute_payment) if request.post?
    end

    def get_allowed_funding_sources
      @get_allowed_funding_sources = api.build_get_allowed_funding_sources(params[:GetAllowedFundingSourcesRequest] || default_api_value)
      @get_allowed_funding_sources_response = api.get_allowed_funding_sources(@get_allowed_funding_sources) if request.post?
    end

    def get_payment_options
      @get_payment_options = api.build_get_payment_options(params[:GetPaymentOptionsRequest] || default_api_value)
      @get_payment_options_response = api.get_payment_options(@get_payment_options) if request.post?
    end

    def payment_details
      @payment_details = api.build_payment_details(params[:PaymentDetailsRequest] || default_api_value)
      @payment_details_response = api.payment_details(@payment_details) if request.post?
    end

    def pay
      @pay = api.build_pay(params[:PayRequest] || default_api_value)
      @pay.ipnNotificationUrl ||= ipn_notify_url
      @pay.returnUrl ||= adaptive_payments_url(:pay)
      @pay.cancelUrl ||= adaptive_payments_url(:pay)
      @pay_response = api.pay(@pay) if request.post?
    end

    def preapproval_details
      @preapproval_details = api.build_preapproval_details(params[:PreapprovalDetailsRequest] || default_api_value)
      @preapproval_details_response = api.preapproval_details(@preapproval_details) if request.post?
    end

    def preapproval
      @preapproval = api.build_preapproval(params[:PreapprovalRequest] || default_api_value)
      @preapproval.ipnNotificationUrl ||= ipn_notify_url
      @preapproval.returnUrl ||= adaptive_payments_url(:preapproval)
      @preapproval.cancelUrl ||= adaptive_payments_url(:preapproval)
      @preapproval_response = api.preapproval(@preapproval) if request.post?
    end

    def refund
      @refund = api.build_refund(params[:RefundRequest] || default_api_value)
      @refund_response = api.refund(@refund) if request.post?
    end

    def set_payment_options
      @set_payment_options = api.build_set_payment_options(params[:SetPaymentOptionsRequest] || default_api_value)
      @set_payment_options_response = api.set_payment_options(@set_payment_options) if request.post?
    end

    def get_funding_plans
      @get_funding_plans = api.build_get_funding_plans(params[:GetFundingPlansRequest] || default_api_value)
      @get_funding_plans_response = api.get_funding_plans(@get_funding_plans) if request.post?
    end

    def get_available_shipping_addresses
      @get_available_shipping_addresses = api.build_get_available_shipping_addresses(params[:GetAvailableShippingAddressesRequest] || default_api_value)
      @get_available_shipping_addresses_response = api.get_available_shipping_addresses(@get_available_shipping_addresses) if request.post?
    end

    def get_shipping_addresses
      @get_shipping_addresses = api.build_get_shipping_addresses(params[:GetShippingAddressesRequest] || default_api_value)
      @get_shipping_addresses_response = api.get_shipping_addresses(@get_shipping_addresses) if request.post?
    end

    def get_user_limits
      @get_user_limits = api.build_get_user_limits(params[:GetUserLimitsRequest] || default_api_value)
      @get_user_limits_response = api.get_user_limits(@get_user_limits) if request.post?
    end

    private

    def api
      @api ||= API.new
    end
  end
end

adaptivepayments-sdk-ruby/samples/app/controllers/adaptive_payments_samples/application_controller.rb
module AdaptivePaymentsSamples
  class ApplicationController < ActionController::Base

    def default_api_value
      t("#{service_name}.#{service_action}", :default => {})
    end

    def service_name
      params[:controller].gsub(/^.*\//, "")
    end

    def service_action
      params[:action]
    end
    helper_method :service_action, :service_name

  end
end

adaptivepayments-sdk-ruby/samples/app/helpers/adaptive_payments_samples/adaptive_payments_helper.rb
module AdaptivePaymentsSamples
  module AdaptivePaymentsHelper
  end
end

adaptivepayments-sdk-ruby/samples/app/helpers/adaptive_payments_samples/application_helper.rb
module AdaptivePaymentsSamples
  module ApplicationHelper
    def active_li(display, link_path, options = {})
      active_menu = options.delete(:match_path) ? request.path =~ Regexp.new(link_path) : request.path == link_path
      content_tag(:li, :class => active_menu ? "active" : "") do
        link_to(display, link_path, options)
      end
    end

    def active_li_regexp(display, link_path, options = {})
      active_li(display, link_path, options.merge(:match_path => true))
    end

    def api_form_for(object, *args, &block)
      options         = args.extract_options!
      options[:as]  ||= api_class_name(object.class)
      simple_form_for(object, *(args << options.merge(:builder => APIFormBuilder, :wrapper => :api_sample_form)), &block)
    end

    def generate_code(api_request, api_response)
      request_hash= api_request.to_hash(:namespace => false, :attribute => false)
      request_hash.delete(:Version)
      # request_hash  = get_dotted_hash(request_hash)
      response_hash = api_response.to_hash(:namespace => false, :attribute => false)
      ruby_code   = render("ruby_code.rb", :api_request => api_request, :api_response => api_response, :request_hash => request_hash, :response_hash => response_hash)
      ruby_code.html_safe
    end

    def get_dotted_hash(hash, prefix = "", values = {})
      max_lenght  = Hash[hash.select{|k, v| !(v.is_a? Hash or v.is_a? Array) }].keys.map(&:size).max
      hash.each do |key, value|
        if value.is_a? Hash
          get_dotted_hash(value, "#{prefix}#{key}.", values)
        elsif value.is_a? Array and value[0].is_a? Hash
          value.each_with_index do |array_value, index|
            get_dotted_hash(array_value, "#{prefix}#{key}[#{index}].", values)
          end
        elsif !value.nil?
          k = sprintf("%s%-#{max_lenght}s", prefix, key)
          values[k] = value
        end
      end
      values
    end

    def format_hash(hash)
      entries = hash.map do |key, value|
        "#{key.to_sym.inspect} => " +
          if value.is_a? Hash and value.size > 0
            format_hash(value)
          elsif value.is_a? Array and value[0].is_a? Hash
            "[" + value.map{|v| format_hash(v) }.join(",") + "]"
          else
            value.to_json
          end
      end
      indent_hash_entries(entries)
    end

    def indent_hash_entries(entries)
      if entries.size > 0
        "{\n" + entries.join(",\n").gsub(/^/, "  ") + " }"
      else
        "{}"
      end
    end

    def api_class_name(klass)
      klass.name.gsub(/^.*::/, "")
    end
  end
end

adaptivepayments-sdk-ruby/samples/app/views/adaptive_payments_samples/adaptive_payments/_phone.html.haml
.control-group
  = phone.label :phoneNumber
  .controls
    = phone.text_field :countryCode, :class => "input-micro"
    = phone.text_field :phoneNumber, :class => "input-small"
    = phone.text_field :extension, :class => "input-mini"

adaptivepayments-sdk-ruby/samples/app/views/adaptive_payments_samples/adaptive_payments/_sidebar.html.erb
<div class="well well-mini">
  <ul class="nav nav-list bs-docs-sidenav">
    <%= active_li "Pay",                      adaptive_payments_path(:pay) %>
    <%= active_li "Payment Details",          adaptive_payments_path(:payment_details) %>
    <%= active_li "Preapproval",              adaptive_payments_path(:preapproval) %>
    <%= active_li "Preapproval Details",      adaptive_payments_path(:preapproval_details) %>
    <%= active_li "Refund",                   adaptive_payments_path(:refund) %>
    <%= active_li "Cancel Preapproval",       adaptive_payments_path(:cancel_preapproval) %>
    <%= active_li "Confirm Preapproval",      adaptive_payments_path(:confirm_preapproval) %>
    <%= active_li "Convert Currency",         adaptive_payments_path(:convert_currency) %>
    <%= active_li "Set Payment Options",      adaptive_payments_path(:set_payment_options) %>
    <%= active_li "Execute Payment",          adaptive_payments_path(:execute_payment) %>
    <%= active_li "Get Payment Options",      adaptive_payments_path(:get_payment_options) %>
  </ul>
</div>

adaptivepayments-sdk-ruby/samples/app/views/adaptive_payments_samples/adaptive_payments/api_response.js.erb
var response_data = <%= render("api_response", :request => @api, :response => @api_response).to_json.html_safe %>;

if($('#response').length == 1){
  $('#response').replaceWith(response_data);
} else {
  $('.span10').append(response_data);
}

adaptivepayments-sdk-ruby/samples/app/views/adaptive_payments_samples/adaptive_payments/cancel_preapproval.html.haml
= api_form_for @cancel_preapproval, :url => adaptive_payments_path(:cancel_preapproval) do |f|

  .row
    .span5
      %legend Cancel preapproval request
      = f.input :preapprovalKey

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @cancel_preapproval_response
  = render 'api_response', :request => @cancel_preapproval, :response => @cancel_preapproval_response

adaptivepayments-sdk-ruby/samples/app/views/adaptive_payments_samples/adaptive_payments/confirm_preapproval.html.haml
= api_form_for @confirm_preapproval, :url => adaptive_payments_path(:confirm_preapproval) do |f|

  .row
    .span5
      %legend Confirm preapproval request
      = f.input :preapprovalKey
      = f.input :fundingSourceId
      = f.input :pin

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @confirm_preapproval_response
  = render 'api_response', :request => @confirm_preapproval, :response => @confirm_preapproval_response

adaptivepayments-sdk-ruby/samples/app/views/adaptive_payments_samples/adaptive_payments/convert_currency.html.haml
= api_form_for @convert_currency, :url => adaptive_payments_path(:convert_currency) do |f|

  .row
    .span5
      %legend From Currency
      = f.fields_for :baseAmountList do |base|
        = base.fields_for :currency do |cur|
          = cur.input :code
          = cur.input :amount

    .span5
      %legend To Currency
      = f.fields_for :convertToCurrencyList do |base|
        .control-group
          %label.control-label Code
          - base.object.currency_code.each do |code|
            .controls
              = text_field_tag "#{base.object_name}[currencyCode][]", code, :class => "input-small"

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing" }

- if @convert_currency_response
  = render 'api_response', :request => @convert_currency, :response => @convert_currency_response

adaptivepayments-sdk-ruby/samples/app/views/adaptive_payments_samples/adaptive_payments/execute_payment.html.haml
= api_form_for @execute_payment, :url => adaptive_payments_path(:execute_payment) do |f|

  .row
    .span5
      %legend Execute payment request
      = f.input :payKey
      = f.input :actionType
      = f.input :fundingPlanId

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @execute_payment_response
  = render 'api_response', :request => @execute_payment, :response => @execute_payment_response

adaptivepayments-sdk-ruby/samples/app/views/adaptive_payments_samples/adaptive_payments/get_payment_options.html.haml
= api_form_for @get_payment_options, :url => adaptive_payments_path(:get_payment_options) do |f|

  .row
    .span5
      %legend Get Payment Options
      = f.input :payKey

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @get_payment_options_response
  = render 'api_response', :request => @get_payment_options, :response => @get_payment_options_response

adaptivepayments-sdk-ruby/samples/app/views/adaptive_payments_samples/adaptive_payments/pay.html.haml
= api_form_for @pay, :url => adaptive_payments_path(:action => :pay) do |f|

  .row
    .span5
      %legend Pay request
      = f.input :actionType, :as => :select, :collection => [ "PAY", "CREATE", "PAY_PRIMARY" ]
      = f.input :cancelUrl
      = f.input :returnUrl
      = f.association :fundingConstraint do |fc|
        = fc.association :allowedFundingType do |aft| # Array
          = aft.association :fundingTypeInfo do |fti|
            = fti.input :fundingType, :as => :select, :collection => [ "ECHECK", "BALANCE", "CREDITCARD" ]
      = f.input :currencyCode
      = f.input :feesPayer,  :as => :select, :collection => [ "SENDER", "EACHRECEIVER", "PRIMARYRECEIVER", "SECONDARYONLY"]
      = f.input :ipnNotificationUrl
      = f.input :memo
      = f.input :pin
      = f.input :preapprovalKey
      = f.input :reverseAllParallelPaymentsOnError, :as => :boolean
      = f.input :senderEmail
      = f.input :trackingId

    .span5
      %legend Receiver
      = f.fields_for :receiverList do |list|
        = list.fields_for :receiver do |receiver|
          = receiver.input :amount
          = receiver.input :email
          = receiver.fields_for :phone do |phone|
            = render 'phone', :phone => phone
          = receiver.input :primary, :as => :boolean
          = receiver.input :invoiceId
          = receiver.input :paymentType, :as => :select, :collection => [ "GOODS", "SERVICE", "PERSONAL", "CASHADVANCE", "DIGITALGOODS" ]
          = receiver.input :paymentSubType

      %legend Sender
      = f.fields_for :sender do |sender|
        = sender.input :useCredentials, :as => :boolean
        = sender.input :email
        = sender.fields_for :phone do |phone|
          = render 'phone', :phone => phone


  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @pay_response
  = render 'api_response', :request => @pay, :response => @pay_response
  - if @pay_response.success?
    = link_to "Redirect URL to Complete Payment", @api.payment_url(@pay_response)

adaptivepayments-sdk-ruby/samples/app/views/adaptive_payments_samples/adaptive_payments/payment_details.html.haml
= api_form_for @payment_details, :as => "PaymentDetailsRequest", :url => adaptive_payments_path(:payment_details) do |f|

  .row
    .span5
      %legend Payment details request
      = f.input :payKey
      = f.input :transactionId
      = f.input :trackingId

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @payment_details_response
  = render 'api_response', :request => @payment_details, :response => @payment_details_response

adaptivepayments-sdk-ruby/samples/app/views/adaptive_payments_samples/adaptive_payments/preapproval.html.haml
= api_form_for @preapproval, :url => adaptive_payments_path(:preapproval) do |f|

  .row
    .span5
      %legend Preapproval request
      =# f.input :clientDetails, ClientDetailsType
      = f.input :cancelUrl
      = f.input :returnUrl
      = f.input :currencyCode
      = f.input :dateOfMonth
      = f.input :dayOfWeek,     :as => :select, :collection => PayPal::SDK::AdaptivePayments::API::DayOfWeek.options
      = f.input :maxAmountPerPayment
      = f.input :maxNumberOfPayments
      = f.input :maxNumberOfPaymentsPerPeriod
      = f.input :maxTotalAmountOfAllPayments
    .span5
      %legend -
      = f.input :startingDate
      = f.input :endingDate # DateTime
      = f.input :paymentPeriod,  :as => :select, :collection => [ "NO_PERIOD_SPECIFIED", "DAILY",
                     "WEEKLY", "BIWEEKLY", "SEMIMONTHLY", "MONTHLY", "ANNUALLY" ]
      = f.input :memo
      = f.input :ipnNotificationUrl
      = f.input :senderEmail
      = f.input :pinType,    :as => :select, :collection => [ "NOT_REQUIRED", "REQUIRED" ]
      = f.input :feesPayer,  :as => :select, :collection => [ "EACHRECEIVER", "PRIMARYRECEIVER", "SENDER", "SECONDARYONLY" ]
      = f.input :displayMaxTotalAmount, :as => :boolean


  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @preapproval_response
  = render 'api_response', :request => @preapproval, :response => @preapproval_response
  - if @preapproval_response.success?
    = link_to "Redirect URL to Complete Preapproval Authorization", @api.preapproval_url(@preapproval_response)

adaptivepayments-sdk-ruby/samples/app/views/adaptive_payments_samples/adaptive_payments/preapproval_details.html.haml
= api_form_for @preapproval_details, :url => adaptive_payments_path(:preapproval_details) do |f|

  .row
    .span5
      %legend Preapproval details request
      = f.input :preapprovalKey

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @preapproval_details_response
  = render 'api_response', :request => @preapproval_details, :response => @preapproval_details_response

adaptivepayments-sdk-ruby/samples/app/views/adaptive_payments_samples/adaptive_payments/refund.html.haml
= api_form_for @refund, :url => adaptive_payments_path(:action => :refund) do |f|

  .row
    .span5
      %legend Refund request
      = f.input :currencyCode
      = f.input :payKey
      = f.input :transactionId
      = f.input :trackingId

    .span5
      %legend Reciver
      = f.fields_for :receiverList do |list|
        = list.fields_for :receiver do |receiver|
          = receiver.input :amount
          = receiver.input :email
          = receiver.fields_for :phone do |phone|
            = render 'phone', :phone => phone


  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @refund_response
  = render 'api_response', :request => @refund, :response => @refund_response